# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0d53b7045ee56eabc8311ff0a006b2060834aba3adc8cbaa27cd49d56ea887029166a4c47f8970947cec94cca341259fbac9c2dd0123ecbef2c569f46c06b50

test:
  secret_key_base: fa2e46dc97d5af4a1ab08d920e0245f2310fa42986f78bf02303be95d82d738466391b1a08151006b6c2bccbfea8988237c2355438e2e4783b4a41a719722109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
